IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'nlp') EXEC('CREATE SCHEMA nlp');
CREATE TABLE nlp.NlpIntent (intent_id varchar(64) NOT NULL PRIMARY KEY, member_id varchar(64) NOT NULL, context_id varchar(64) NOT NULL, intent_type tinyint NOT NULL, original_text nvarchar(4000) NOT NULL, normalized_text nvarchar(4000) NOT NULL, status varchar(32) NOT NULL, expires_at datetimeoffset(7) NOT NULL, created_at datetimeoffset(7) NOT NULL CONSTRAINT DF_NlpIntent_created DEFAULT SYSUTCDATETIME(), version int NOT NULL CONSTRAINT DF_NlpIntent_version DEFAULT 1);
CREATE INDEX IX_NlpIntent_ContextMemberStatusExpires ON nlp.NlpIntent(context_id, member_id, status, expires_at);
CREATE TABLE nlp.NlpEmbedding (intent_id varchar(64) NOT NULL, model_version varchar(128) NOT NULL, dimensions int NOT NULL, normalized_hash char(64) NOT NULL, embedding varbinary(max) NOT NULL, created_at datetimeoffset(7) NOT NULL CONSTRAINT DF_NlpEmbedding_created DEFAULT SYSUTCDATETIME(), CONSTRAINT PK_NlpEmbedding PRIMARY KEY(intent_id, model_version), CONSTRAINT FK_NlpEmbedding_Intent FOREIGN KEY(intent_id) REFERENCES nlp.NlpIntent(intent_id));
CREATE TABLE nlp.NlpRankingConfig (ranking_version varchar(128) NOT NULL PRIMARY KEY, weights_json nvarchar(2000) NOT NULL, threshold decimal(9,6) NOT NULL, active_from datetimeoffset(7) NOT NULL, active_to datetimeoffset(7) NULL, version int NOT NULL DEFAULT 1);
CREATE TABLE nlp.NlpModelVersion (model_version varchar(128) NOT NULL PRIMARY KEY, provider varchar(128) NOT NULL, dimensions int NOT NULL, preprocessing_version varchar(128) NOT NULL, active bit NOT NULL, created_at datetimeoffset(7) NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE nlp.NlpMatchResult (id bigint IDENTITY PRIMARY KEY, request_id varchar(64) NOT NULL, requester_id varchar(64) NOT NULL, candidate_id varchar(64) NOT NULL, score decimal(9,6) NOT NULL, reason_codes nvarchar(1000) NOT NULL, reason_text nvarchar(2000) NOT NULL, model_version varchar(128) NOT NULL, preprocessing_version varchar(128) NOT NULL, ranking_version varchar(128) NOT NULL, created_at datetimeoffset(7) NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT UQ_NlpMatchResult_RequestCandidate UNIQUE(request_id, candidate_id));
CREATE INDEX IX_NlpMatchResult_Request ON nlp.NlpMatchResult(request_id);
CREATE TABLE nlp.NlpFeedback (id bigint IDENTITY PRIMARY KEY, request_id varchar(64) NOT NULL, requester_id varchar(64) NOT NULL, candidate_id varchar(64) NOT NULL, label varchar(64) NOT NULL, reason nvarchar(1000) NULL, created_at datetimeoffset(7) NOT NULL DEFAULT SYSUTCDATETIME());
