<Project Sdk="Microsoft.NET.Sdk.Worker"><PropertyGroup><AssemblyName>Olga.Nlp.Worker</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="..\Olga.Nlp.Infrastructure\Olga.Nlp.Infrastructure.csproj" /><PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" /></ItemGroup></Project>
